{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "agent-messenger.fullname" . }}
  labels:
    {{- include "agent-messenger.labels" . | nindent 4 }}
spec:
  {{- if .Values.persistence.existingClaim }}
  volumeName: {{ .Values.persistence.existingClaim }}
  {{- end }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}