"""
Agent Messenger SDK — Python client for self-hosted messaging between humans and AI agents.
"""

__version__ = "0.1.0"

from .types import (
    Agent,
    AgentConfig,
    ClientConfig,
    Conversation,
    CreateConversationRequest,
    EditMessageRequest,
    EncryptedMessage,
    HealthResponse,
    KeyBundle,
    LoginRequest,
    LoginResponse,
    MarkReadResponse,
    Message,
    PresenceEntry,
    RateLimitInfo,
    ReactRequest,
    ReactResponse,
    Reaction,
    RegisterAgentRequest,
    RegisterAgentResponse,
    RegisterUserRequest,
    RegisterUserResponse,
    SearchMessagesResponse,
    SetRateLimitTierRequest,
    StoreEncryptedMessageRequest,
    Tag,
    TagRequest,
    UploadAttachmentResponse,
    UploadKeyBundleRequest,
    WSChatData,
    WSConnectedData,
    WSErrorData,
    WSMessage,
    WSMessageSentData,
    WSReadReceiptData,
    WSReactionData,
    WSStatusData,
    WSTypingData,
    WSEventType,
)
from .rest import RestClient, ApiError
from .websocket import ClientWS, AgentWS
from .client import AgentMessengerClient, AgentClient

__all__ = [
    "__version__",
    "Agent",
    "AgentConfig",
    "AgentClient",
    "AgentMessengerClient",
    "ApiError",
    "ClientConfig",
    "ClientWS",
    "AgentWS",
    "Conversation",
    "CreateConversationRequest",
    "EditMessageRequest",
    "EncryptedMessage",
    "HealthResponse",
    "KeyBundle",
    "LoginRequest",
    "LoginResponse",
    "MarkReadResponse",
    "Message",
    "PresenceEntry",
    "RateLimitInfo",
    "ReactRequest",
    "ReactResponse",
    "Reaction",
    "RegisterAgentRequest",
    "RegisterAgentResponse",
    "RegisterUserRequest",
    "RegisterUserResponse",
    "RestClient",
    "SearchMessagesResponse",
    "SetRateLimitTierRequest",
    "StoreEncryptedMessageRequest",
    "Tag",
    "TagRequest",
    "UploadAttachmentResponse",
    "UploadKeyBundleRequest",
    "WSChatData",
    "WSClientConfig",
    "WSConnectedData",
    "WSErrorData",
    "WSMessage",
    "WSMessageSentData",
    "WSReadReceiptData",
    "WSReactionData",
    "WSStatusData",
    "WSTypingData",
    "WSEventType",
]